### ISSUE TITLE
Unable to compile Win64 binary with mingw on Kali from 1.11.5

### ISSUE THREAD

**Issue by MikeLim7** [rbsec/sslscan#147]
Unable to compile latest release on Kali with mingw-w64

>/usr/bin/x86_64-w64-mingw32-gcc -I/tmp/openssl/include -DVERSION=\""1.11.10 Windows 64-bit (Mingw)"\"  -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Wl,-O1 -Wl,--discard-all -Wl,--no-undefined -Wl,--dynamicbase -Wl,--nxcompat -static -o sslscan.exe sslscan.c /tmp/openssl/libssl.a /tmp/openssl/libcrypto.a -lws2_32 -lgdi32 
>sslscan.c: In function ‘tcpConnect’:
>sslscan.c:479:13: warning: implicit declaration of function ‘strnstr’ [-Wimplicit-function-declaration]
    if (strnstr(buffer, ok, BUFFERSIZE)) {
>             ^
>sslscan.c: In function ‘testCipher’:
>sslscan.c:1487:9: warning: implicit declaration of function ‘gettimeofday’ [-Wimplicit-function-declaration]
>         gettimeofday(&tval_start, NULL);
>         ^
>sslscan.c:1690:21: warning: implicit declaration of function ‘timersub’ [-Wimplicit-function-declaration]
>                     timersub(&tval_end, &tval_start, &tval_elapsed);
>                    ^
>/tmp/ccWStnbe.o:sslscan.c:(.text+0x149f): undefined reference to `strnstr'

>/tmp/ccWStnbe.o:sslscan.c:(.text+0x1508): undefined reference to `strnstr'

>/tmp/ccWStnbe.o:sslscan.c:(.text+0x4786): undefined reference to `timersub'

>collect2: error: ld returned 1 exit status

>Makefile.mingw:39: recipe for target 'sslscan' failed

>make: *** [sslscan] Error 1

Seems that mingw does not have definitions for strnstr and timersub.  Was able to compile with 11.4-rbsec as it does not use strnstr() and timersub()

**Comment by rbsec** [comment]
How are you trying to cross-compile? I've just tested on a clean Kali build, and it works fine. Looking at your command above, you don't seem to have zlib1 installed.

```
$ sudo apt install zlib1g-dev mingw-w64 build-essential
$ sudo apt built-dep openssl
$ git clone https://github.com/rbsec/sslscan
$ cd sslscan
$ make -f Makefile.mingw
```

**Comment by MikeLim7** [comment]
I downloaded  latest release ZIP file and followed the INSTALL instructions, which are different from what you did. 


Using your steps, I got it compiled on Kali. Steps  below for future reference

`Edit /etc/apt/sources and un-comment deb-src line`
> sudo apt-get update
> sudo apt install zlib1g-dev mingw-w64 build-essential
> sudo apt build-dep openssl
> cd /opt
> git clone https://github.com/rbsec/sslscan
> cd sslscan
> make -f Makefile.gw

Thanks! Now I have the latest build. 

Happy 2018 to all! Version 1.11.10 Windows 64-bit build attached for those who wants it. :-) 
[sslscan.zip](https://github.com/rbsec/sslscan/files/1594901/sslscan.zip)
